development:
  secret_key_base: super_long_secret_key_for_development
  google_client_id: 893778344541-3jcm22uhmk3h959bcp0hv0ff2t15la65.apps.googleusercontent.com
  google_client_secret: 3T3i0sxiHsfOr89-DXtl5Z-N